/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef uctest_CONSTANTS_H
#define uctest_CONSTANTS_H

#include "uctest_types.h"

namespace uctest {

class uctestConstants {
 public:
  uctestConstants();

};

extern const uctestConstants g_uctest_constants;

} // namespace

#endif
